### ISSUE TITLE
Block is empty. 

### ISSUE THREAD

**Issue by 321cheese123** [nick99nack/JSBingoSlots#1]
I was playing Slingo casually when a block with no number appeared after I spun.
How to recreate: Play slingo a few times until a block in the bottom right corner appears with no number. Or, in another area idk.
This is already on the discord and here's the image. 
![image](https://user-images.githubusercontent.com/70666613/123170047-6f9d8b00-d450-11eb-85a3-f2fac46f591b.png)

**Comment by nick99nack** [comment]
I think this was fixed a while ago. Haven't seen it pop up recently.
